CORE = base

VSRC = \
    address.v \
    bsx.v \
    cheat.v \
    clk_test.v \
    config.vh \
    ctx.v \
    dac.v \
    dcm.v \
    dma.v \
    main.v \
    mcu_cmd.v \
    msu.v \
    rtc.v \
    sd_dma.v \
    spi.v \
    srtc.v

VHSRC =

COMMON_IP = dac_buf msu_databuf snescmd_buf

HEADER = config.vh

XIL_IP =
XIL_IPCORE_DIR = ipcore_dir

INT_IP = pll

include ../settings.mk
include ../common.mk
